### ISSUE TITLE
Opening Mellis in the windows start menu does not respond

### ISSUE THREAD

**Issue by ArtoriaShirou** [themeliolabs/mellis#17]
Opening Mellis in the windows start menu does not respond.
But it can be opened from the desktop shortcut created during installation.

I think it may be a problem with the start-up parameters

![image](https://user-images.githubusercontent.com/95868829/165837034-6b8457b3-a826-4adc-a5ae-0240d589d60f.png)

**Comment by nullchinchilla** [comment]
Fixed in v0.3.0
