### ISSUE TITLE
Windows Defender has Trojan alert

### ISSUE THREAD

**Issue by ArtoriaShirou** [themeliolabs/mellis#18]
Windows Defender has Trojan false positives:

![image](https://user-images.githubusercontent.com/95868829/165837271-57c3d6f8-6b6a-4565-acc0-6bf0054b3bd7.png)

**Comment by nullchinchilla** [comment]
That's very strange because virustotal only has "Cynet" saying it's a virus: https://www.virustotal.com/gui/file/6720eae38cbdcb24c2b7fc505e6eacb7eae755bb5a2d6b5ff75b893ba82aa79a/detection

When does this false positive happen? Is it caught by Windows Defender's real-time protection, or a scan?

**Comment by ArtoriaShirou** [comment]
It is caught by Windows Defender's real-time protection, I can record a video to illustrate the situation.

**Comment by nullchinchilla** [comment]
sure, it'll be very helpful to see what sort of actions triggers it.

**Comment by ArtoriaShirou** [comment]
Sorry, I had some problems debugging the GIF recording tool and it took a lot of time.

The GIF:

![video_fast(1)](https://user-images.githubusercontent.com/95868829/166613815-9e31d5f8-a520-48f3-80b6-e49a6f26c1a6.gif)

**Comment by nullchinchilla** [comment]
Fixed in v0.3.0
