### ISSUE TITLE
Duplicate sending problem

### ISSUE THREAD

**Issue by ArtoriaShirou** [themeliolabs/mellis#19]
Sometimes when sending tokens, Confirm is clicked, but the 'Send assets' screen remains on the front end:

![image](https://user-images.githubusercontent.com/95868829/166242658-48672897-2bb2-41d3-942e-6c0fdccade27.png)

When Confirm is clicked again, an error occurs:

![image](https://user-images.githubusercontent.com/95868829/166242737-d31348d4-f99b-4550-90e4-97f2d800a23d.png)

At this point, although the transaction has been successfully submitted, but you cannot exit this screen, you can only restart the wallet.

My Settings:

![image](https://user-images.githubusercontent.com/95868829/166245157-c14b0bc9-65c9-48f1-9188-a61105de8259.png)

**Comment by nullchinchilla** [comment]
Fixed in v0.3.0
