### ISSUE TITLE
Bar disappears

### ISSUE THREAD

**Issue by ArtoriaShirou** [themeliolabs/mellis#38]
The Bar disappears when the Transcations page is opened.

This issue was discovered by **_Captain 雪ノ下八幡#4209_** in the Discord community.

Environment Info:

- System: macOS Monterey 12.3.1(21E258)
- Wallet Version: v0.3.1 or v0.3.2

Picture:

![image](https://user-images.githubusercontent.com/95868829/168836013-21b44cd3-038e-440a-86dd-26fd4e66e4fe.png)

**Comment by nullchinchilla** [comment]
v0.3.6 should have fixed this.
